export type Lang = "en" | "te";

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    appName: "AI Placement Mentor",
    tagline: "Your personalized guide to placement success, tailored for Tier-2 & Tier-3 students.",
    dashboard: "Dashboard",
    roadmap: "Roadmap Generator",
    mockInterview: "AI Mock Interview",
    skillGap: "Skill Gap Quiz",
    projects: "Project Guide",
    tracker: "Streak Tracker",
    resumeBuilder: "Resume Builder",
    resumeSub: "Build and evaluate an ATS-ready resume with real-time feedback.",
    aptitudeArena: "Aptitude Arena",
    aptitudeSub: "Learn and practice aptitude concepts with simple Telugu explanations.",
    jobBoard: "Job Alerts",
    jobSub: "Latest off-campus job alerts for freshers and Tier-2/3 graduates.",
    welcomeBack: "Welcome back, Learner!",
    currentStreak: "Current Streak",
    days: "days",
    overallProgress: "Overall Placement Readiness",
    dailyTarget: "Daily Target",
    weeklyGoal: "Weekly Goal Status",
    completed: "Completed",
    pending: "Pending",
    activeGoals: "Today's Focus Tasks",
    toggleLanguage: "తెలుగు",
    roadmapTitle: "Generate Your Personalized Roadmap",
    roadmapSub: "Get a step-by-step preparation plan tailored to your profile.",
    selectBranch: "Select Your Branch",
    selectLevel: "Your Current Technical Level",
    selectGoal: "Your Career Goal",
    selectDuration: "Preparation Duration",
    beginner: "Beginner (No coding experience)",
    intermediate: "Intermediate (Know basics, simple code)",
    advanced: "Advanced (Can solve DSA, build projects)",
    serviceBased: "Service Companies (TCS, Infosys, Wipro)",
    productBased: "Product Startups & Mid-scale Companies",
    faangLevel: "FAANG / High-Growth Companies",
    months3: "3 Months (Fast Track)",
    months6: "6 Months (Balanced)",
    months12: "12 Months (Comprehensive)",
    generateRoadmap: "Generate Placement Roadmap",
    interviewTitle: "AI Mock Interview Arena",
    interviewSub: "Practice HR and Technical rounds. Speak or type your answers to get instant, actionable feedback.",
    startInterview: "Start Interview Session",
    selectRound: "Select Interview Type",
    technicalRound: "Technical Interview (DSA, OOPs, Web)",
    hrRound: "HR Interview (Behavioral, Culture Fit)",
    aiMLRound: "AI/ML Engineer Interview (Python, ML models)",
    interviewerTyping: "Interviewer is analyzing your response...",
    submitAnswer: "Submit Answer",
    endSession: "End Interview & Get Report",
    feedbackScore: "Interview Score",
    feedbackTechnical: "Technical Performance",
    feedbackComm: "Communication Skills",
    feedbackImprovement: "Areas to Improve",
    skillGapTitle: "Placement Skill Gap Analyzer",
    skillGapSub: "Test yourself in Coding, Quantitative Aptitude, and English Communication to find your gaps.",
    startQuiz: "Start Assessment Quiz",
    quizCompleted: "Quiz Completed! Generating Skill Gap Report...",
    gapScorecard: "Placement Readiness Gap Scorecard",
    strengths: "Your Key Strengths",
    weaknesses: "Skill Gaps Identified",
    actionPlan: "Recommended Actions to Bridge Gaps",
    projectsTitle: "Placement-Ready Projects",
    projectsSub: "Build hands-on projects that recruiters actually care about. Select your stack below.",
    domainFilter: "Filter by Domain",
    all: "All Domains",
    webDev: "Web Development",
    aiML: "AI & Machine Learning",
    mobileApp: "Mobile Apps",
    techStack: "Tech Stack",
    difficulty: "Difficulty",
    viewGuide: "View Step-by-Step Guide",
    trackerTitle: "Daily Consistency Tracker",
    trackerSub: "Placements are won by small daily habits. Maintain your streak to stay motivated.",
    habitList: "Daily Habit Checklist",
    habit1: "Solve 1 Coding Challenge (LeetCode/GFG)",
    habit2: "Practice 5 Quantitative Aptitude Problems",
    habit3: "Read 1 Technical Concept or Explain it Aloud",
    habit4: "Update your resume / Apply to 1 opportunity",
    habit5: "Practice English Speaking (2 minutes)",
    streakBoard: "Consistency Grid (Last 30 Days)",
    motivationalQuote: "Daily Wisdom",
    backToDashboard: "Go to Dashboard",
    selectLanguagePrompt: "Select Language / భాష ఎంచుకోండి:",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    education: "Education Details",
    skillsList: "Technical Skills (comma separated)",
    projectsDesc: "Project Description & Achievements",
    experience: "Work Experience / Internships",
    atsScore: "ATS AI Review Score",
    runAIEvaluation: "Analyze Resume (AI Review)",
    printResume: "Print / Save PDF Resume",
    showSolution: "Show Explanation",
    nextQuestion: "Next Question",
    applyNow: "Apply Now",
    applied: "✓ Applied Successfully"
  },
  te: {
    appName: "AI ప్లేస్‌మెంట్ మెంటర్",
    tagline: "టైర్-2 & టైర్-3 విద్యార్థుల కోసం ప్రత్యేకంగా రూపొందించబడిన మీ వ్యక్తిగత ప్లేస్‌మెంట్ గైడ్.",
    dashboard: "డ్యాష్‌బోర్డ్",
    roadmap: "రోడ్‌మ్యాప్ జనరేటర్",
    mockInterview: "AI మాక్ ఇంటర్వ్యూ",
    skillGap: "స్కిల్ గ్యాప్ క్విజ్",
    projects: "ప్రాజెక్ట్ గైడ్",
    tracker: "స్ట్రీక్ ట్రాకర్",
    resumeBuilder: "రెజ్యూమ్ బిల్డర్",
    resumeSub: "ఏటీఎస్ (ATS) ఆధారిత రెజ్యూమ్‌ను సృష్టించి రివ్యూ చేసుకోండి.",
    aptitudeArena: "ఆప్టిట్యూడ్ అరేనా",
    aptitudeSub: "ఆప్టిట్యూడ్ ప్రశ్నలను తెలుగు వివరణలతో నేర్చుకోండి.",
    jobBoard: "ఉద్యోగ అవకాశాలు",
    jobSub: "ఫ్రెషర్స్ మరియు డిగ్రీ విద్యార్థుల కోసం తాజా ఉద్యోగ సమాచారం.",
    welcomeBack: "స్వాగతం, విద్యార్థి!",
    currentStreak: "ప్రస్తుత స్ట్రీక్",
    days: "రోజులు",
    overallProgress: "మొత్తం ప్లేస్‌మెంట్ సన్నద్ధత",
    dailyTarget: "రోజువారీ లక్ష్యం",
    weeklyGoal: "వారపు లక్ష్యాల స్థితి",
    completed: "పూర్తయినవి",
    pending: "పెండింగ్",
    activeGoals: "నేటి ముఖ్యమైన పనులు",
    toggleLanguage: "English",
    roadmapTitle: "మీ వ్యక్తిగత రోడ్‌మ్యాప్‌ను సృష్టించండి",
    roadmapSub: "మీ నైపుణ్యాల ఆధారంగా ఒక స్పష్టమైన ప్రిపరేషన్ ప్లాన్ పొందండి.",
    selectBranch: "మీ బ్రాంచ్ ఎంచుకోండి",
    selectLevel: "మీ ప్రస్తుత కోడింగ్ స్థాయి",
    selectGoal: "మీ కెరీర్ లక్ష్యం",
    selectDuration: "ప్రిపరేషన్ సమయం",
    beginner: "బిగినర్ (కోడింగ్ అనుభవం లేదు)",
    intermediate: "ఇంటర్మీడియట్ (బేసిక్స్ తెలుసు, చిన్న ప్రోగ్రామ్స్ రాయగలరు)",
    advanced: "అడ్వాన్స్డ్ (DSA సాల్వ్ చేయగలరు, ప్రాజెక్ట్స్ చేయగలరు)",
    serviceBased: "సర్వీస్ కంపెనీలు (TCS, Infosys, Wipro)",
    productBased: "ప్రొడక్ట్ స్టార్టప్స్ & మిడ్-స్కేల్ కంపెనీలు",
    faangLevel: "FAANG / పెద్ద ఐటీ కంపెనీలు",
    months3: "3 నెలలు (ఫాస్ట్ ట్రాక్ ప్రిపరేషన్)",
    months6: "6 నెలలు (సమతుల్య ప్రిపరేషన్)",
    months12: "12 నెలలు (పూర్తి స్థాయి ప్రిపరేషన్)",
    generateRoadmap: "రోడ్‌మ్యాప్ జనరేట్ చేయండి",
    interviewTitle: "AI మాక్ ఇంటర్వ్యూ అరేనా",
    interviewSub: "HR మరియు టెక్నికల్ రౌండ్లు ప్రాక్టీస్ చేయండి. తెలుగు లేదా ఇంగ్లీషులో సమాధానాలు ఇచ్చి తక్షణ ఫీడ్‌బ్యాక్ పొందండి.",
    startInterview: "ఇంటర్వ్యూ ప్రారంభించండి",
    selectRound: "ఇంటర్వ్యూ రకాన్ని ఎంచుకోండి",
    technicalRound: "టెక్నికల్ ఇంటర్వ్యూ (DSA, OOPs, వెబ్ డెవలప్‌మెంట్)",
    hrRound: "HR ఇంటర్వ్యూ (వ్యక్తిగత ప్రవర్తన, ఆటిట్యూడ్)",
    aiMLRound: "AI/ML ఇంజనీర్ ఇంటర్వ్యూ (పైథాన్, ML మోడల్స్)",
    interviewerTyping: "ఇంటర్వ్యూయర్ మీ సమాధానాన్ని విశ్లేషిస్తున్నారు...",
    submitAnswer: "సమాధానం పంపండి",
    endSession: "ఇంటర్వ్యూ ముగించి రిపోర్ట్ చూడండి",
    feedbackScore: "ఇంటర్వ్యూ స్కోర్",
    feedbackTechnical: "సాంకేతిక ప్రదర్శన (Technical skills)",
    feedbackComm: "కమ్యూనికేషన్ నైపుణ్యాలు (Communication)",
    feedbackImprovement: "మెరుగుపరుచుకోవాల్సిన అంశాలు",
    skillGapTitle: "ప్లేస్‌మెంట్ నైపుణ్యాల విశ్లేషణ (Skill Gap Analyzer)",
    skillGapSub: "మీ గ్యాప్స్ గుర్తించడానికి కోడింగ్, ఆప్టిట్యూడ్, మరియు ఇంగ్లీష్ కమ్యూనికేషన్‌లో చిన్న క్విజ్ రాయండి.",
    startQuiz: "పరీక్ష ప్రారంభించండి",
    quizCompleted: "క్విజ్ పూర్తయింది! నైపుణ్యాల విశ్లేషణ రిపోర్ట్ జనరేట్ అవుతోంది...",
    gapScorecard: "ప్లేస్‌మెంట్ గ్యాప్ రిపోర్ట్",
    strengths: "మీ బలమైన నైపుణ్యాలు",
    weaknesses: "మీరు మెరుగుపరుచుకోవాల్సిన నైపుణ్యాలు",
    actionPlan: "గ్యాప్ పూరించడానికి చేయాల్సిన పనులు",
    projectsTitle: "ప్లేస్‌మెంట్ ఆధారిత ప్రాజెక్ట్స్",
    projectsSub: "రిక్రూటర్లను ఆకట్టుకునే ప్రాజెక్టులను నిర్మించండి. కింద ఉన్న వాటిలో ఎంచుకోండి.",
    domainFilter: "డొమైన్ ఎంచుకోండి",
    all: "అన్ని డొమైన్లు",
    webDev: "వెబ్ డెవలప్‌మెంట్",
    aiML: "AI & మెషిన్ లెర్నింగ్",
    mobileApp: "మొబైల్ యాప్స్",
    techStack: "టెక్నాలజీలు",
    difficulty: "కఠినత స్థాయి",
    viewGuide: "ప్రాజెక్ట్ గైడ్ చూడండి",
    trackerTitle: "రోజువారీ నిలకడ ట్రాకర్",
    trackerSub: "రోజూ చేసే చిన్న ప్రయత్నాలే పెద్ద విజయాలను ఇస్తాయి. మీ స్ట్రీక్‌ను కొనసాగించండి.",
    habitList: "రోజువారీ చేయాల్సిన పనుల లిస్ట్",
    habit1: "1 కోడింగ్ ప్రాబ్లెమ్ సాల్వ్ చేయడం (LeetCode/GFG)",
    habit2: "5 ఆప్టిట్యూడ్ క్వశ్చన్స్ ప్రాక్టీస్ చేయడం",
    habit3: "1 టెక్నికల్ కాన్సెప్ట్ చదవడం లేదా పైకి వివరించడం",
    habit4: "రెజ్యూమ్ అప్డేట్ చేయడం / 1 జాబ్‌కి అప్లై చేయడం",
    habit5: "2 నిమిషాలు ఇంగ్లీషులో మాట్లాడటం ప్రాక్టీస్ చేయడం",
    streakBoard: "నిలకడ గ్రిడ్ (గడిచిన 30 రోజులు)",
    motivationalQuote: "ఈరోజు మంచి మాట",
    backToDashboard: "డ్యాష్‌బోర్డ్‌కి వెళ్ళండి",
    selectLanguagePrompt: "భాషను ఎంచుకోండి / Select Language:",
    fullName: "పూర్తి పేరు",
    email: "ఈమెయిల్ చిరునామా",
    phone: "ఫోన్ నంబర్",
    education: "చదువు వివరాలు",
    skillsList: "సాంకేతిక నైపుణ్యాలు (కామాతో విడదీసి రాయండి)",
    projectsDesc: "ప్రాజెక్ట్ వివరాలు & విజయాలు",
    experience: "పని చేసిన అనుభవం / ఇంటర్న్‌షిప్",
    atsScore: "ATS AI రివ్యూ స్కోర్",
    runAIEvaluation: "రెజ్యూమ్ విశ్లేషణ చేయండి (AI రివ్యూ)",
    printResume: "ప్రింట్ / PDF సేవ్ చేసుకోండి",
    showSolution: "వివరణ చూడండి",
    nextQuestion: "తదుపరి ప్రశ్న",
    applyNow: "అప్లై చేయండి",
    applied: "✓ అప్లై చేయడం విజయవంతమైంది"
  }
};
